name: Keep Supabase Project Alive

on:
  schedule:
    # Roda às 12:00 UTC todas as segundas, quartas e sextas-feiras
    - cron: '0 12 * * 1,3,5'
  workflow_dispatch: # Permite executar o teste manualmente pelo botão no GitHub

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send API request to Supabase
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          curl -f -X GET "https://zmxytngunmyuscmncdmx.supabase.co/rest/v1/" \
            -H "apikey: $SUPABASE_KEY" \
            -H "Authorization: Bearer $SUPABASE_KEY"